---
  parser: "@babel/eslint-parser"

  extends: "standard"

  plugins: ["flowtype", "import", "chai-friendly"]

  rules:
    space-before-function-paren: [2, {"anonymous": "always", "named": "never"}]
    comma-dangle: [2, "only-multiline"]
    no-var: 2
    prefer-const: 2
    padded-blocks: 0
    arrow-parens: 0
    no-multiple-empty-lines: 0
    no-return-assign: 0
    generator-star-spacing: 0
    no-duplicate-imports: 0

    indent: ["error", 2, {"SwitchCase": 1, "MemberExpression": 1}]
    indent-legacy: "off"

    no-return-await: "off"

    flowtype/define-flow-type: 2
    flowtype/use-flow-type: 2

    import/no-duplicates: "off"

