dockergen: docker-gen -watch -wait 100ms:500ms -event-filter event=connect -event-filter event=disconnect -notify "nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
nginx: nginx -g "daemon off;"
status: sh -c 'case "$NAVY_STATUS_ENDPOINT" in 1|true|yes|TRUE|YES|True|Yes) exec perl /app/status-helper.pl;; *) exec sleep infinity;; esac'
