name: navy CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: node-${{ matrix.node-version }} docker-${{ matrix.docker }} compose-${{ matrix.docker_compose }}
    env:
      DEBUG: "navy:*"
      NAVY_DEBUG: "navy:*"
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]
        docker: [18.06-dind, 20.10.5-dind]
        docker_compose: [1.29.2, v2.10.2]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        env:
          DOCKER_TAG: ${{matrix.docker}}
          DOCKER_COMPOSE_VERSION: ${{matrix.docker_compose}}
          GITHUB_NODE_VERSION: ${{matrix.node-version}}
        with:
          node-version: ${{ matrix.node-version }}
      - name: Before tests
        run: node --version
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
