name: navy CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: node ${{ matrix.node }}
    env:
      DEBUG: 'navy:*' NAVY_DEBUG='navy:*' DOCKER_COMPOSE_VERSION=1.29.2

    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 14.x]
        docker: [18.06-dind, 20.10.5-dind]
        docker_compose: [1.14.0, 1.29.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        env:
          DOCKER_TAG: ${{matrix.docker}}
          DOCKER_COMPOSE_VERSION: ${matrix.docker_compose}}
        with:
          node-version: ${{ matrix.node }}
      - name: Before tests
        run: node --version
        run: npm ci
        run: npm run bootstrap

      - name: Test
        run: npm test


